services:
  ordersservice:
    image: ${DOCKER_REGISTRY-}ordersservice
    build:
      context: .
      dockerfile: OrdersService/Dockerfile
    ports:
      - "5000:8080"
  notificationservice:
    image: ${DOCKER_REGISTRY-}notificationservice
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    ports:
      - "5001:8080"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # RabbitMQ UI
